openapi: 3.0.0
servers: []
info:
  description: This document explains how to list available restaurants and create an order.
  version: "1.0.0"
  title: Delivery App API
  contact:
    email: dev@deliveryapp.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: restaurant
    description: Restaurant, Menu and Category endpoints
  - name: order
    description: Order related endpoints
paths:
  /restaurant:
    get:
      tags:
        - restaurant
      summary: list available restaurants
      operationId: getAvailableRestaurants
      description: |
        Returns list of available restaurants that can be order with restaurant menu.
      responses:
        '200':
          description: list of restaurants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /order:
    get:
      tags:
        - order
      summary: list user orders
      operationId: getUserOrders
      responses:
        '200':
          description: list of user orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: Bad request
        '403':
          description: Unauthorized
        '500':
          description: Internal server error
    post:
      tags:
        - order
      summary: create new order
      operationId: createOrder
      requestBody:
        description: Order details,
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderPayload'
      responses:
        '200':
          description: Order creation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad request
        '403':
          description: Unauthorized
        '500':
          description: Internal server error
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    CreateOrderPayload:
      type: object
      properties:
        restaurant:
          type: number
          example: 1
          description: restaurant id
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    Order:
      type: object
      required:
        - id
        - user
        - status
        - items
        - created_at
        - modified_at
      properties:
        id:
          type: number
          example: 1
        user:
          type: number
          example: 3
          description: Order creating user id
        status:
          $ref: '#/components/schemas/OrderStatus'
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        created_at:
          type: string
          format: datetime
          example: '2021-11-20T00:10:17.843000Z'
        modified_at:
          type: string
          format: datetime
          example: '2021-11-20T00:10:17.843000Z'
    OrderStatus:
      description: Order current status
      type: string
      enum:
        - CREATED
        - PREPARING
        - ON_THE_WAY
        - DELIVERED
    OrderItem:
      type: object
      required:
        - count
        - menu_item
      properties:
        count:
          type: number
          example: 1
          description: amount of menu item
        menu_item:
          type: number
          example: 2
          description: MenuItem id
    Restaurant:
      type: object
      required:
        - id
        - name
        - menu
        - created_at
        - modified_at
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: 'Süper Dönerci'
        menu:
          type: array
          items:
            $ref: '#/components/schemas/MenuItem'
        created_at:
          type: string
          format: datetime
          example: '2021-11-20T00:10:17.843000Z'
        modified_at:
          type: string
          format: datetime
          example: '2021-11-20T00:10:17.843000Z'
    MenuItem:
      type: object
      required:
        - id
        - name
        - category
        - created_at
        - modified_at
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: 'İskender'
        category:
          $ref: '#/components/schemas/Category'
        created_at:
          type: string
          format: datetime
          example: '2021-11-20T00:10:17.843000Z'
        modified_at:
          type: string
          format: datetime
          example: '2021-11-20T00:10:17.843000Z'
    Category:
      type: object
      description: Menu item cuisine
      required:
        - id
        - name
        - created_at
        - modified_at
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: 'Döner / Kebap'
        created_at:
          type: string
          format: datetime
          example: '2021-11-20T00:10:17.843000Z'
        modified_at:
          type: string
          format: datetime
          example: '2021-11-20T00:10:17.843000Z'
security:
  - basicAuth: []