version: '3.2'

services:
  api:
    build:
      context: api
    container_name: delivery-api
    restart: unless-stopped
    volumes:
      - ./api:/usr/src/app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  consumer:
    build:
      context: api
    container_name: delivery-consumer
    restart: unless-stopped
    command: python manage.py startconsumers
    volumes:
      - ./api:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.1
    container_name: delivery-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.6
    container_name: delivery-redis
    restart: unless-stopped

volumes:
  pgdata:
