version: '3.2'

services:
  api:
    build:
      context: api
    container_name: delivery-api
    restart: unless-stopped
    volumes:
      - ./api:/usr/src/app
    environment:
      - DEBUG=true
      - SECRET=top-secret-key
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.1
    container_name: delivery-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.6
    container_name: delivery-redis
    restart: unless-stopped

volumes:
  pgdata:
